language: python
services: mongodb
python:
  - "2.7"
  - "3.3"
install:
  - "pip install -r requirements.txt --use-mirrors"
before_script:
  - python setup.py develop
script:
  - nosetests
  - source fireworks/tests/cmd_line_test.sh
notifications:
  email:
    recipients:
      - ajain@lbl.gov
      - dkgunter@lbl.gov
      - ongsp@ucsd.edu
      - xqu@lbl.gov
    on_success: change
    on_failure: always