language: python
services: mongodb
python:
  - "2.7"
  - "3.1"
  - "3.3"
install:
  - "pip install -r requirements.txt --use-mirrors"
before_script:
  - python setup.py develop
script:
  - nosetests
  - lpad get_wfs -d more
  - lpad get_fws -d more
  - rlaunch singleshot
notifications:
  email:
    recipients:
      - ajain@lbl.gov
    on_success: change
    on_failure: always